export const PRODUCT_IMAGE_VECTOR_DATABASE = `https://dear-cougar-66323-eu1-vector.upstash.io`;

export const UPSTACH_VECTOR_DATABASE_TOKEN = `ABUFMGRlYXItY291Z2FyLTY2MzIzLWV1MWFkbWluWTJRNU0yUm1NR0V0TWpRNFppMDBNRFU0TFRrd1l6TXRabVV5WVdOaVl6WTRabUl3`;
